### ISSUE TITLE
Cookie sync 500 response when bidder is not enabled

### ISSUE THREAD

**Issue by muuki88** [prebid/prebid-server-java#1137]
## Expected behaviour

Cookie sync should work even when a bidder is part of the `s2sConfig.bidders` that is not yet active on prebid server.

## Actual behaviour

`/cookie_sync` returns a 500.

```
Unexpected setuid processing error: null
```

## Steps to reproduce

1. On the prebid server deactive one of them
```yaml
adapters:
  appnexus:
    enabled: true
  rubicon:
    enabled: false
```
2. Fire a cookie sync request, e.g. http://localhost:8000/cookie_sync with this json body
```json
{"uuid":"8675c874-ec89-4bff-8d2d-4b23b530680e","bidders":["appnexus","rubicon"],"account":"1","gdpr":1,"gdpr_consent":"CPBHEa4PBHEa4AGABCENBLCgAP_AAH_AAAYgHBtf_X9fb2_j-_5999t0eY1f9_63v-wzjgeNs-8NyZ_X_L4Xt2MyvB34pq4KmR4Eu3LBAQdlHGHcTQmQwIkVqTLsak2Mr7NKJ7JEilMbe2dYGH9vn8XT_ZKY70_____7_3-_____77YAAIAAAAAAAAAAgZeAQYAAoAAAIIAAgQKEQgAAhDEgAAAACKEQCASQAJFAAMrgIpAAIAEBiAhAgBACChBgEAAgAASQBACAFAgEABEAgABAAIAQAAIAAQWAEgIAAAIASEABEAEIEBBEABByGBARAEEAKACAqMgKgAUABUAEMAJgAXABHADLAGpAPsA_ACMAEcAKWAVsA3gCYgE2ALRAWwAwIBh4DIhEBsAFQAVgAuACGAGQAMsAagA2QB-AEAAIwAUsAp4BrAD5AIbAQ6Ai8BIgCbAE7AKRAXIAwIBhIDDwGTiQAIADhAAEBdASCOAAgABcAFAAVAAyABwADwAIAARAAqABhADQANQAeQBDAEUAJkAVQBWACwAFwAN4AcwA9ACGgEQARIAlgBNAClAGGAMgAZcA1ADVAGyAO8AewA-IB9gH6AQAAjABHAClgFPAL8AYoA1gBtADcAG8APQAfIBDYCHQEVAIvASIAmIBMoCbAE7AKHAUiAsUBbAC5AF3gMCAYMAwkBhoDDwGRAMkAZOAy4KABAGEEABgDNAXkAyMNAfABUAFYALgAhgBkADLAGoANkAfgBAACCgEYAKWAU-AtAC0gGsAN4AfIBDYCHQEXgJEATYAnYBSIC5AGBAMJAYeAxgBk4cACAA4MABAXQKgLgAUABUAEMAJgAXABHADLAGoAPwAjABHAClwFoAWkA3gCQQExAJsAU2AtgBcgDAgGHgMiHQUQAFwAUABUADIAHAAQAAiABVADAAMYAaABqADwAH0AQwBFACZAFUAVgAsABcADEAGYAN4AcwA9ACGAEQAJYATAAmgBRgClAFiAMMAZAAygBogDUAGyAN8Ad4A9oB9gH6ARYAjABHACUgFPALFAWgBaQC5gF5AL8AYoA2gBuIDpgOoAegBDYCHQERAIvASCAkQBNgCdgFDgKaAVYAsWBbAFsgLgAXIAu0Bd4DCQGGgMPAYkAxgBjwDJAGTgMqAZcPAAgIqHABwAHAAXAGaARkAuoB8gEyEIFwACwAKAAZABEACoAGIAQwAmABVAC4AGIAMwAbwA9ACOAFiAMoAagA3wB3wD7APwAjABHACUgFDAKfAWgBaQC_AGKANoAdQA9ACQQEiAJsAU0AsUBaMC2ALaAXAAuQBdoDDwGJAMiAZOQAAgEZJQKgAEAALAAoABkADgAIoAYABiADwAIgATAAqgBcADEAGYANoAhoBEAESAKMAUoAwgBlADVAGyAO8AfgBGACOAFPgLQAtIBigDcAHUAQ6Ai8BIgCbAFigLYAXaAw8BkQDJyYAEBFRIAGABcAjIBPikD0ABcAFAAVAAyABwAEAAIgAVQAwADGAGgAagA8gCGAIoATAApABVACwAFwAMQAZgA5gCGAEQAKMAUoAsQBlADRAGqANkAd8A-wD9AIsARgAjgBKQChgFbALmAXkA2gBuAD0AIdAReAkQBNgCdgFDgKaAVsAsUBbAC4AFyALtAYaAw8BjADIgGSAMnAZcUABAAXAJEAA.YAAAAAAAAAAA"}
```

If you want to replicate this with a prebid.js distribution you need to add bidder to the `s2sConfig` that is not active in prebid.js
```js
s2sConfig: {
  bidders: [ appnexusAst, rubicon ]
}
```

## Research

The NPE appears here:
https://github.com/prebid/prebid-server-java/blob/7c65f2f482607912c6c38dadb9de38c710743783/src/main/java/org/prebid/server/privacy/gdpr/tcfstrategies/purpose/typestrategies/FullEnforcePurposeStrategy.java#L88

as the `vendorId` is null and the `com.iabtcf.utils.IntIterable#contains`  method takes an `int`, not and `Integer`.

The vendorId is `null` as the bidder is not marked as active here.
https://github.com/prebid/prebid-server-java/blob/7c65f2f482607912c6c38dadb9de38c710743783/src/main/java/org/prebid/server/auction/BidderAliases.java#L60-L62

## Suggestion

If the `vendorId` is null the restriction type is `NOT_ALLOWED` as the bidder is marked inactive and thus shouldn't  be allowed to drop cookies. WDYT?

**Comment by DGarbar** [comment]
Yeah. Thanks for pointing that and creating PR to cover that. 

P. S. If you're wondering why we have such a workflow. We need to pass bidder name to TCF module even if we can't match any vendor id for it, because Host can exclude it (by name) in configuration.

**Comment by muuki88** [comment]
I think this is resolved now, right?
