### ISSUE TITLE
Incorrect param name in appnexus

### ISSUE THREAD

**Issue by pavel-ptashyts** [prebid/prebid-server-java#1286]
In org.prebid.server.bidder.appnexus.proto.AppnexusImpExtAppnexus param placementId  is send in json as "placementId ", but correct name is "placement_id". Please check  go implementation of adapter

https://github.com/prebid/prebid-server/blob/master/adapters/appnexus/appnexus.go
line =70
Also check this assumption on real data.
If send "placementId" = always 204 no bid
If  send "placement_id" = 200 bids

**Comment by snahornyi** [comment]
@pavel-ptashyts 
As yo can see
```java
@Value
public class AppnexusImpExtAppnexus {

    Integer placementId;
```
As default property naming strategy we use snake case, so it will be converted to this
```json
"placement_id": 9880618
```    
You can verify it in our integration tests

**Comment by pavel-ptashyts** [comment]
Hi thanks for clarification
