### ISSUE TITLE
Pubmatic adapter only uses adSlot param for banners

### ISSUE THREAD

**Issue by jbartek25** [prebid/prebid-server-java#1341]
I'm using PBS for video HB and Pubmatic adapter (based on the info in pubmatic.yaml) supports video. I couldn't find my video requests/imps in Pubmatic reporting and on closer look at the bid requests sent to Pubmatic, the adapter code [here](https://github.com/prebid/prebid-server-java/blob/master/src/main/java/org/prebid/server/bidder/pubmatic/PubmaticBidder.java#L128) only ever passes the adapter `adSlot` param for the banner requests (in imp.tagid field) but not for any other media type. I believe this is a bug as after modifying the adapter to set imp.tagid for video I see the bids in Pubmatic reports + Pubmatic started bidding much more frequently than before.

**Comment by rpanchyk** [comment]
Hi @jbartek25 
We've ported the code from Go - https://github.com/prebid/prebid-server/blob/e7f7b558951684f1fb75bc4c180506cdc91b5f98/adapters/pubmatic/pubmatic.go#L160
Actually, they do the same.

Technically, we can fix it but sure if it ok from requirements. @bretg can you help?

**Comment by jbartek25** [comment]
@rpanchyk any logic setting tagid in the Java adapter runs only for banners whereas the logic in Go [here](https://github.com/prebid/prebid-server/blob/e7f7b558951684f1fb75bc4c180506cdc91b5f98/adapters/pubmatic/pubmatic.go#L404) seemingly runs for all ad types. I see tagid populated in PBS Go requests but not PBS Java so bits of logic got missed in the Java port.

**Comment by rpanchyk** [comment]
ahhh... thank you guys, was looking into old `Call(..)` instead of `MakeRequests(..)` method.
Btw, didn't expect imp modification in `validateAdSlot(..)` method.
Anyway, we'll fix the port.

**Comment by jbartek25** [comment]
@rpanchyk thank you

**Comment by snahornyi** [comment]
Code of Pubmatic adapter updated in linked PR, so now everything worked as expected
