### ISSUE TITLE
Tappx Adaptater out of date

### ISSUE THREAD

**Issue by prebidtappx** [prebid/prebid-server-java#1407]
Hi, I'm Albert Grandes from Tappx.
Some of our publishers use the magnite adapter. However, we have had problems with these publishers because the magnite adapter is not up to date with the latest changes to the prebid adapter in go.
In the latest version of prebid Server we add new parameters (https://github.com/prebid/prebid-server/commit/c01c993fb5f0c86475f9650fbea6369a7cb3780e).
Also, in another commit we made important changes that should be integrated into the java adapter (https://github.com/prebid/prebid-server/pull/1777).
Thanks for everything.

**Comment by rpanchyk** [comment]
Hi Albert, we're on track with changes in Tappx and will implement they next week.

**Comment by rpanchyk** [comment]
https://github.com/prebid/prebid-server-java/pull/1410 merged. Closing.
