### ISSUE TITLE
Only one Timeout Resolver is being used

### ISSUE THREAD

**Issue by muuki88** [prebid/prebid-server-java#1520]
We discovered a lot of timeouts recently and discovered that the timeout settings for the auction are not respected. Instead the defaults are being used.

https://github.com/prebid/prebid-server-java/blob/bfaa4b84eea5452d33e47ae6df499774d0086562/src/main/resources/application.yaml#L93-L95

It seems that there's only *one* `TimeoutResolver` wired everywhere:

https://github.com/prebid/prebid-server-java/blob/bfaa4b84eea5452d33e47ae6df499774d0086562/src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java#L161-L168

I guess the responsible line is this

https://github.com/prebid/prebid-server-java/blob/bfaa4b84eea5452d33e47ae6df499774d0086562/src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java#L218

**Comment by rpanchyk** [comment]
Thank you @muuki88 ! Great catch!
