### ISSUE TITLE
'integration' config vs 'channel' config

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server-java#1524]
It was pointed out in https://github.com/prebid/prebid-server/issues/1428 that PBS-Java's config uses confusing terminology.

"channel" is supposed to take values like "amp" and "app". It represents the major path taken by the request.

"integration" is supposed to take values like "ios", "mpbjs", etc -- specific details about the source within the channel. 

There are couple of places where this config is used:
- enabling privacy features
- analytics config

The config and code label the options as "integration", but then utilize channel-like values:

```
// IntegrationType enumerates the values of integrations Prebid Server can configure for an account
type IntegrationType string

// Possible values of integration types Prebid Server can configure for an account
const (
	IntegrationTypeAMP   IntegrationType = "amp"
	IntegrationTypeApp   IntegrationType = "app"
	IntegrationTypeVideo IntegrationType = "video"
	IntegrationTypeWeb   IntegrationType = "web"
)
```
and
```
{
  "id": "1111",
  "status": "active",
  "auction": {
    ...
    "default-integration": "web",
  }
...
  "privacy": {
    "ccpa": {
      "enabled": true,
      "integration-enabled": {
          "web": true,
          "amp": false,
          "app": true,
          "video": false
      }
    },

```

@rpanchyk - please confirm that these configurations actually look at ext.prebid.channel.name despite being called `integration-enabled`. Assuming so, please rename the code, config, and docs to align the terminology to `channel-enabled`.

**Comment by rpanchyk** [comment]
hi @bretg !

1. Confirmed to rename `privacy.ccpa.integration-enabled` to `privacy.ccpa.channel-enabled` (with backward compatibility for transition period).

2. What about the GDPR:  `privacy.gdpr.integration-enabled` to `privacy.gdpr.channel-enabled` ? Suppose, worth to change as well.

3. To be on the same page, i'm not following how `ext.prebid.channel.name` and `integration-enabled` relates to each other ?
Seems `ext.prebid.channel.name` is comparing with `analytics.auction-events.<channel>` account config property to add vast tracking and create `bid.ext.prebid.events` in response.

**Comment by bretg** [comment]
1. thanks
2. yes please
3. privacy.gdpr.channel-enabled and privacy.ccpa.channel-enabled should use the values seen in ext.prebid.channel.name

For instance:
```
  "privacy": {
    "ccpa": {
      "enabled": true,
      "channel-enabled": {
          "web": true,     // if ext.prebid.channel.name=="web"
          "amp": false,   // if ext.prebid.channel.name=="amp"
          "app": true,     // if ext.prebid.channel.name=="app"
          "video": false  // if ext.prebid.channel.name=="video"
      }
    },
```
