### ISSUE TITLE
external-url not used in RubiconConfiguration

### ISSUE THREAD

**Issue by muuki88** [prebid/prebid-server-java#1564]
https://github.com/prebid/prebid-server-java/blob/711bfa44c5319d310f61c2f42b3e6ce489022d19/src/main/java/org/prebid/server/spring/config/bidder/RubiconConfiguration.java#L45

Is this on purpose :smile: ? IMHO the `externalUrl` should be used in the `UserSyncer`, right?

**Comment by rpanchyk** [comment]
Yeah, but not each bidder requires it. Rubicon doesn't need redirect url.

**Comment by muuki88** [comment]
I stumbled upon this as I fixed this in our code to make rubicon work :smile:

**Comment by rpanchyk** [comment]
So... do we have here to do anything?

**Comment by muuki88** [comment]
In our internal fork we add the `externalUrl` to the UserSyncCreator, depending on your judgement you can keep leave it null here or add it :shrug: :smile:
