### ISSUE TITLE
Question: Make changes to Java version of adapter

### ISSUE THREAD

**Issue by curlyblueeagle** [prebid/prebid-server-java#1632]
We, at 33Across, would like to recommend making the following changes to our bid adapter. What is the best practice to do so? To have us make a PR or for the Prebid dev team to make them?

1. Add caller info, like the [Go version does](https://github.com/prebid/prebid-server/blob/master/adapters/33across/33across.go#L191). This didn't get ported over?
2. Rename our adapter from `TTX` to `ThirtyThreeAcross` as naming is extremely important to us in terms of bidder recognition from partners.

**Comment by curlyblueeagle** [comment]
@rpanchyk so I have already made the changes in my fork. Can I make a PR against your repo?

**Comment by rpanchyk** [comment]
ah cool, sure - go ;)

**Comment by curlyblueeagle** [comment]
thanks! I will file the PR after the holidays as we don't want to make any new releases.
