### ISSUE TITLE
Metrics for HTTP 4xx responses

### ISSUE THREAD

**Issue by muuki88** [prebid/prebid-server-java#1715]
Hi folks,

We would like to monitor the 4xx repsonses from prebid server via the integrated metrics.
This would be useful, because

* a single configuration issue fails the auction, which we would like to detect as fast as possible
* the metrics are easy to integrate in existing monitoring / alerting systems

Ideally the metrics contain the `accountId` so it's easy to trace back, which account is misconfigured or sends invalid requests.
A metric may look like this

```
account.<account-id>.requests.rejected.(invalid-account|invalid-stored-impr|invalid-stored-request)
```

If the `account.<account-id>.requests.rejected` is kept as is this shouldn't even be a breaking change and the old metric can be deprecated.

**Comment by bretg** [comment]
@muuki88 - is this request just breaking out the account.request.rejected metric or bigger? PBS will respond with 4xx in other cases like JSON validation, and modules could decide to reject for pretty much any reason.

**Comment by muuki88** [comment]
Only breaking out the reject metric.

**Comment by bretg** [comment]
Opened an internal ticket, but can't promise when it will get done. If you have your team do this @muuki88 , would suggest placing them place these metrics in the 'basic' verbosity level. i.e.  metrics.accounts.basic-verbosity

**Comment by muuki88** [comment]
Thanks a lot. If we find time for this in the next quarter I'll ping you, so we don't waste engineering time 😊

**Comment by bretg** [comment]
Discussed in PBS committee. Approved.

We would be interested in making account-related metrics level (basic/verbose) configurable at the account level, but that can be a separate enhancement.
