### ISSUE TITLE
test java server locally problem

### ISSUE THREAD

**Issue by kachok1213** [prebid/prebid-server-java#1830]
Hi
How can I test the java server locally?
I followed the instructions, cloned proj ,built with mvn, and its running and looks ok
then i sent /status and got 200 - ok till here its all looks good
then i tried /auction with the sample in prebid , and getting the following error:
Error occurred while populating bid request: Host is not defined or can not be derived from request

i guess its because im on localhost, i had another problem before with the request ip, but x-forwarded-for fixed it
however, x-forwarded-host not worked.
any help? thanks a lot !

**Comment by SerhiiNahornyi** [comment]
Hi, @kachok1213!
This is example of headers, I always add to my requests

``` http
Referer: http://www.example.com
X-Forwarded-For: 192.168.244.1
Origin: http://www.example.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
```
Add them to your request.
If it will help you, pls close this issue.
If no, I would like to see your full http request.

**Comment by kachok1213** [comment]
@SerhiiNahornyi thank you for your response!
unfortunately it didnt solved it, my request is:


{
  "id": "some-request-id",
  "test": 1,
  
  "site": {
    "page": "prebid.org"
  },
  "imp": [{
    "id": "some-impression-id",
    "debug": true,
    "banner": {
      "format": [{
        "w": 600,
        "h": 500
      }, {
        "w": 300,
        "h": 600
      }]
    },
    "ext": {
        
      "prebid": {
        "bidder": {
          "appnexus": {
            "placementId": 12883451
          }
        }
      }
    }
  }],
  "tmax": 500
}
and the response is:
id": "some-request-id",
    "seatbid": [],
    "cur": "USD",
    "nbr": 0,
    "ext": {
        "debug": {
            "resolvedrequest": {
                "id": "some-request-id",
                "imp": [
                    {
                        "id": "some-impression-id",
                        "banner": {
                            "format": [
                                {
                                    "w": 600,
                                    "h": 500
                                },
                                {
                                    "w": 300,
                                    "h": 600
                                }
                            ]
                        },
                        "ext": {
                            "prebid": {
                                "bidder": {
                                    "appnexus": {
                                        "placementId": 12883451
                                    }
                                }
                            }
                        }
                    }
                ],
                "site": {
                    "page": "prebid.org",
                    "ext": {
                        "amp": 0
                    }
                },
                "device": {
                    "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",
                    "ip": "79.177.63.88"
                },
                "test": 1,
                "at": 1,
                "tmax": 500,
                "cur": [
                    "USD"
                ],
                "source": {
                    "tid": "fac77093-43f3-4cd1-821f-ddb68656068d"
                }
            }
        },
        "responsetimemillis": {},
        "tmaxrequest": 500,
        "prebid": {
            "auctiontimestamp": 1650440362957
        }
    }
}

instead of:

{
  "id": "some-request-id",
  "seatbid": [{
    "seat": "appnexus",
    "bid": [{
      "id": "145556724130495288",
      "impid": "some-impression-id",
      "price": 0.01,
      "adm": "<script type=\"application/javascript\">...</script>",
      "adid": "107987536",
      "adomain": [
        "appnexus.com"
      ],
      "iurl": "https://nym1-ib.adnxs.com/cr?id=107987536",
      "cid": "3532",
      "crid": "107987536",
      "w": 600,
      "h": 500,
      "ext": {
        "prebid": {
          "type": "banner",
          "video": {
            "duration": 0,
            "primary_category": ""
          }
        },
        "bidder": {
          "appnexus": {
            "brand_id": 1,
            "auction_id": 7311907164510136364,
            "bidder_id": 2,
            "bid_ad_type": 0
          }
        }
      }
    }]
  }],
  "cur": "USD",
  "ext": {
    "responsetimemillis": {
      "appnexus": 10
    },
    "tmaxrequest": 500
  }
}

with this error in the server:
[ntloop-thread-1] .p.s.a.r.Ortb2ImplicitParametersResolver : Error occurred while populating bid request: Host is not defined or can not be derived from request
thank you again!

**Comment by SerhiiNahornyi** [comment]
@kachok1213 Value of PBS property `gdpr.default-value` is 0 or 1? 
If 1, pls add regs object for request
```java
"regs": {
    "ext": {
      "gdpr": 0
    }
  }
``` 
Let me know if this helped you

**Comment by kachok1213** [comment]
well, its not solved it but i got new error

`{
    "id": "some-request-id",
    "seatbid": [],
    "cur": "USD",
    "nbr": 0,
    "ext": {
        "debug": {
            "resolvedrequest": {
                "id": "some-request-id",
                "imp": [
                    {
                        "id": "some-impression-id",
                        "banner": {
                            "format": [
                                {
                                    "w": 600,
                                    "h": 500
                                },
                                {
                                    "w": 300,
                                    "h": 600
                                }
                            ]
                        },
                        "ext": {
                            "prebid": {
                                "bidder": {
                                    "appnexus": {
                                        "placementId": 12883451
                                    }
                                }
                            }
                        }
                    }
                ],
                "site": {
                    "page": "prebid.org",
                    "ext": {
                        "amp": 0
                    }
                },
                "device": {
                    "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",
                    "ip": "79.177.63.88"
                },
                "test": 1,
                "at": 1,
                "tmax": 500,
                "cur": [
                    "USD"
                ],
                "source": {
                    "tid": "b561d3a0-8804-42e4-b0d8-7cd8468a5376"
                },
                "regs": {
                    "ext": {
                        "gdpr": 0
                    }
                }
            }
        },
        "errors": {
            "appnexus": [
                {
                    "code": 2,
                    "message": "appnexus is not configured properly on this Prebid Server deploy. If you believe this should work, contact the company hosting the service and tell them to check their configuration."
                }
            ]
        },
        "responsetimemillis": {
            "appnexus": 0
        },
        "tmaxrequest": 500,
        "prebid": {
            "auctiontimestamp": 1650458165805
        }
    }
}`



this is the new error :
appnexus is not configured properly on this Prebid Server deploy. If you believe this should work, contact the company hosting the service and tell them to check their configuration
what does it mean? and do you think its associated with my first error? ( cannot resolve host from request ) 
thank you!

**Comment by SerhiiNahornyi** [comment]
@kachok1213 You need to enable appnexus adapte.
Pls add `adapters.appnexus.enabled=true` property

**Comment by kachok1213** [comment]
@SerhiiNahornyi  hi
where should I add this prop? 
at test-application.properties file?? 
im pretty new with this, thank you!

**Comment by kachok1213** [comment]
@SerhiiNahornyi 
ok now the response is 

`{
    "id": "some-request-id",
    "seatbid": [],
    "cur": "USD",
    "nbr": 0,
    "ext": {
        "debug": {
            "httpcalls": {
                "appnexus": [
                    {
                        "uri": "http://ib.adnxs.com/openrtb2",
                        "requestbody": "{\"id\":\"some-request-id\",\"imp\":[{\"id\":\"some-impression-id\",\"banner\":{\"format\":[{\"w\":600,\"h\":500},{\"w\":300,\"h\":600}],\"w\":600,\"h\":500},\"ext\":{\"appnexus\":{\"placement_id\":12883451}}}],\"site\":{\"page\":\"prebid.org\",\"ext\":{\"amp\":0}},\"device\":{\"ua\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36\",\"ip\":\"79.177.63.88\"},\"test\":1,\"at\":1,\"tmax\":500,\"cur\":[\"USD\"],\"source\":{\"tid\":\"6583c09f-4284-47c2-b409-3b8606987cf7\"},\"regs\":{\"ext\":{\"gdpr\":0}},\"ext\":{\"appnexus\":{\"is_amp\":0,\"hb_source\":5}}}",
                        "requestheaders": {
                            "Accept": [
                                "application/json"
                            ],
                            "x-prebid": [
                                "pbs-java/1.87.0"
                            ],
                            "Content-Type": [
                                "application/json;charset=utf-8"
                            ]
                        }
                    }
                ]
            },
            "resolvedrequest": {
                "id": "some-request-id",
                "imp": [
                    {
                        "id": "some-impression-id",
                        "banner": {
                            "format": [
                                {
                                    "w": 600,
                                    "h": 500
                                },
                                {
                                    "w": 300,
                                    "h": 600
                                }
                            ]
                        },
                        "ext": {
                            "prebid": {
                                "bidder": {
                                    "appnexus": {
                                        "placementId": 12883451
                                    }
                                }
                            }
                        }
                    }
                ],
                "site": {
                    "page": "prebid.org",
                    "ext": {
                        "amp": 0
                    }
                },
                "device": {
                    "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",
                    "ip": "79.177.63.88"
                },
                "test": 1,
                "at": 1,
                "tmax": 500,
                "cur": [
                    "USD"
                ],
                "source": {
                    "tid": "6583c09f-4284-47c2-b409-3b8606987cf7"
                },
                "regs": {
                    "ext": {
                        "gdpr": 0
                    }
                }
            }
        },
        "errors": {
            "appnexus": [
                {
                    "code": 1,
                    "message": "Timeout period of 98ms has been exceeded"
                }
            ]
        },
        "responsetimemillis": {
            "appnexus": 213
        },
        "tmaxrequest": 500,
        "prebid": {
            "auctiontimestamp": 1650462910022
        }
    }
}`

looks better I think, but still got the error in the server log 

2022-04-20 16:55:09.769  WARN 4680 --- [ntloop-thread-1] .p.s.a.r.Ortb2ImplicitParametersResolver : Error occurred while populating bid request: Host is not defined or can not be derived from request

also this one becuse of the example req so I think its all good?
2022-04-20 16:55:10.014  WARN 4680 --- [ntloop-thread-1] o.p.server.bidder.HttpBidderRequester    : Error occurred while sending HTTP request to a bidder url: http://ib.adnxs.com/openrtb2 with message: Timeout period of 98ms has been exceeded

**Comment by SerhiiNahornyi** [comment]
@kachok1213 
Update request tmax to 5000 
`"tmax": 5000`

**Comment by kachok1213** [comment]
thank you so much!
now i get the bid back! 
 then i can ignore the host issue?

**Comment by SerhiiNahornyi** [comment]
@kachok1213 
About host issue, this one is just PBS log, in 99% everything you should know, you will see in response.
If you feel this issue resolved, pls close.
