### ISSUE TITLE
Logging of Bidder request body after hooks execution

### ISSUE THREAD

**Issue by eshaanmangal** [prebid/prebid-server-java#1888]
We are logging bidder request body in "http-interaction.log" before invoking hooks. So what is happening right now is that I have started using ortb-blocking module but I can't get the values of bcat, badv in http-logging.log that is going in bidder request because we are logging request body before invoking hooks. Infact we are using some custom extra modules as well in our Managed Prebid  which is modifying the request (adding some meta data) but we are logging vanilla request body to  bidder in logs. So can we change this logic ? Can we call function "maybeLogBidderRequest" just before we are making a call to bidder instead of calling it before "invokeHooksAndRequestBids" in ExchangeService ? 

Thanks

**Comment by bretg** [comment]
@SerhiiNahornyi - please take a look and confirm this proposal. Perhaps @eshaanmangal would be open to making this change in a PR if the design is approved.

**Comment by SerhiiNahornyi** [comment]
Done in request above

**Comment by bretg** [comment]
released with PBS-Java 1.97
