### ISSUE TITLE
Warning if `flushingCounter` is used with prometheus

### ISSUE THREAD

**Issue by rmattis** [prebid/prebid-server-java#1891]
As seen below, the default metricType is the `flushingCounter`. This is not a good default if you use a pulling metric system like prometheus. 
https://github.com/prebid/prebid-server-java/blob/69042cdb84beaf41f388e561ebf525125da0249b/docs/config-app.md?plain=1#L222 

We also had this problem and collected wrong metrics for nearly two years. 

I would suggest to show a warning when prometheus is used in combination with the `flushingCounter`, so you have a chance to change the `metricType` when using prometheus as metrics collector.

**Comment by ngjmcdonald** [comment]
Can you elaborate on why this is a bad combination? Or is there any other documentation around this? The only thing I can find is what's described in that [config](https://github.com/prebid/prebid-server-java/blob/master/docs/config-app.md). It's not entirely clear to me what each metric type means. Is there a recommendation for which one to use when prometheus is used?

**Comment by muuki88** [comment]
Hi @ngjmcdonald 

If you use a metric system that receives values via push (e.g. OpenTSDB) it's the systems responsibility when and what metrics are being pushed. Each push resets the metrics and retries may appear, but the counter is only reset once and the values are only read once. Or during rolling deployments each system that startsup starts fresh and pushes appear always in the same time period.

In a pulling system (e.g. prometheus) this works differently. If the `metrics` endpoint is called twice, you will see different results even if the metrics may have not changed, which is wrong. A `GET` call by a prometheus scraper should not alter the metrics. Only the system itself should alter the metrics. Retries, devs or other healthcheck systems calling the metrics endpoint will all alter the metrics, making them invalid.

**Comment by muuki88** [comment]
Clarified with Amy: We use `counter` instead of `flushingCounter`

**Comment by SerhiiNahornyi** [comment]
https://github.com/prebid/prebid-server-java/pull/1909

**Comment by SerhiiNahornyi** [comment]
Resolved in https://github.com/prebid/prebid-server-java/pull/1909
