### ISSUE TITLE
Need the ability to set custom config in Accounts

### ISSUE THREAD

**Issue by mnishihan** [prebid/prebid-server-java#1999]
To serve one of our business requirements, we need to configure accounts with shared custom attributes (which is not currently possible due to the rigid structure of [org.prebid.server.settings.model.Account](https://github.com/prebid/prebid-server-java/blob/master/src/main/java/org/prebid/server/settings/model/Account.java)) and consume that custom configuration from multiple hook modules. In current implementation `Account` is neither derived from [org.prebid.server.proto.openrtb.ext.FlexibleExtension](https://github.com/prebid/prebid-server-java/blob/master/src/main/java/org/prebid/server/proto/openrtb/ext/FlexibleExtension.java) nor has any `ext` attribute of `ObjectNode`/`ExtAccount` type.

So, to have extensibility like most of the other ORTB entities, we propose to have an `ext` attribute of `ObjectNode` type in `Account` model. If approved, we'll be happy to contribute the extension via a PR.

@bretg do you see any issue with this extension??

**Comment by Net-burst** [comment]
Configuration is rigid for a reason. Could you please provide more details about what you are trying to achieve? Thanks.

**Comment by mnishihan** [comment]
@Net-burst Thanks for your reply.

We would like our different custom modules to share some of the same params and this is currently not possible without duplicating the params in `module.hooks.<moduleName>`. 

In our findings it would be very much beneficial to have a simple ext property of ObjectNode type in Account model, that can be used by PBS-Java hosting companies to define their own publisher specific custom configuration to be consumed by their custom hook modules or simply to add additional account details for ad ops convenience (for example account name that will be displayed in the PBS config UI). In my respective PR, I've added that ext property in Account module and verified that all tests are passing and nothing is broken (which is expected, as this property never existed to be used by the core 😊). As a result, from functionality perspective this addition of ext property does not harm, rather adding some flexibility.

> Configuration is rigid for a reason.

Bid requests and imps are not rigid - both have `ext` fields. Account is also not rigid already as hooks config supports arbitrary params and in order to share the same params between different modules we could create a fake module with a sole purpose of being a home for shared params but that option is hacky. `acccount.ext` would be a much cleaner solution.

Thanks again for looking into this.

**Comment by muuki88** [comment]
The use case definitely sounds valid. I assume you run an internal fork with your custom modules ( so do we ).

I would have added those module configs in a separate namespace in the internal fork Account model. While I agree that `ext` is used a lot in the OpenRTB models, this is done IMHO because it's a standard which requires some sort of flexibility. Modelling config as typed classes is IMHO always superior to "put in here what ever you want".

Having that said I really appreciate you contributing this back. However I would not use it , because altering the account config or even reading from other sources is not a big deal in our internal fork.

**Comment by mnishihan** [comment]
@muuki88 As I mentioned earlier, solving our requirements with hacks (running an internal fork is the biggest hack IMHO) is definitely possible, but nobody like hacks, when there is/could be a cleaner way of doing things. So, eventually I'm trying to contribute with my findings & suggestions. And this is the beauty of developing and using open source softwares. Ain't it?? 😊

**Comment by muuki88** [comment]
True 😊 

I see the module condig as part of the module. So adding it to the account config is IMHO not a hack 😁 

`ext` is so vague and there are a lot of other possibilities to configure a module, which is why I get @Net-burst point. This must be maintained in the future as anybody could rely on an extension that can do anything.

**Comment by bretg** [comment]
Would this be solved with module-level config @mnishihan ? That's a feature that's on the list, just haven't gotten around to specing it yet.

I don't particularly like the idea of account ext config, but let me see if I actually understand it. The scenario is that you have two linked modules: moduleA1 and moduleA2. 

Currently you have to configure them separately:
```
{
    "hooks": {
      "modules": {
        "moduleA1": {
          "attributes": {
             "sharedAuthKey": "12345",
              "privateAttr1": "a"
           }
         },
         "moduleA2": {
          "attributes": {
             "sharedAuthKey": "12345",  // repeated config
             "privateAttr2": "b"
           }
         }
      }
    }
}
```
You find duplicating this config ugly, so you'd like to have a shared config:
```
{
    "hooks": {
      "shared-module-config": [{
           "modules": ["moduleA1", "moduleA2"],
           "attributes": {
               "sharedAuthKey": "12345"
           }
       }],
      "modules": {
        "moduleA1": {
          "attributes": {
             "privateAttr1": "a"
           }
         },
         "moduleA2": {
          "attributes": {
             "privateAttr2": "b"
           }
         }
      }
    }
}
```
Is that the general idea? If so, why don't you just combine moduleA1 and moduleA2? It's expected that modules can operate at different hooks.

Here are soe requirements:
1) For security, it's required that modules not be able to see each other's config. This implies that a list of permissions is required.
2) Modules should not have to look somewhere else to get their config. i.e. PBS-core must deliver the config to the module.

So generically adding ORTB-like "ext" functionality is not a very good solution, IMO. If you'd like to build an appropriately-permissioned "shared-module-config" feature that merges the shared config so modules are none-the-wiser, I've no problem with that.

**Comment by mnishihan** [comment]
@bretg sorry for replying late. Thanks a lot for clarifying the reasons that are restricting the team to add an `ext` in `Account` model.

1. Sharing config across multiple modules is not the only requirement we have. We are storing all the accounts (imps, requests as well) in our config backend in a generic structure and have an authenticated UI to manage those via a JSON Schema validated JSON editor. And for that management UI, beside prebid module specific settings, we also need to store some custom account specific custom attributes (for example a human readable name etc.). So, to having an `account.ext` would simplify our case significantly, and extending our JSON Schema for the `account.ext` to support custom attribute definitions would be the only thing that we would need to ensure data validity.
2. Is the following structure already supported for defining shared hook module config? Or this is what you are suggesting to be implemented in my PR?

> ```
> 
> {
>     "hooks": {
>       "shared-module-config": [{
>            "modules": ["moduleA1", "moduleA2"],
>            "attributes": {
>                "sharedAuthKey": "12345"
>            }
>        }],
>       "modules": {
>         "moduleA1": {
>           "attributes": {
>              "privateAttr1": "a"
>            }
>          },
>          "moduleA2": {
>           "attributes": {
>              "privateAttr2": "b"
>            }
>          }
>       }
>     }
> }
> 
> ```

3.  I'm not sure, whether the `appropriately-permissioned "shared-module-config" feature` can actually be useful, as like any other spring bean, hook modules can have `ApplicationSettings` instance injected to them and call any of the methods define there, including `getAccountById`. So, no matter how an implementation tries to restrict access to module specific attributes, there will always be an option to load entire account (which is probably already in cache) via a call of `ApplicationSettings.getAccountById` method and use that any way required.

Anyway, as we have primarily a philosophical difference on the requirement and implementation, we have decided to close this issue (along with respective PR) and use the alternate ways to meet our requirements. As we are writing and using only our own hook modules with custom logic, the access control to account attributes is not a concern to us, so the alternate ways will be enough for us, just not be our preferred option.

Thanks to all the participants for your time in this discussion. ❤️ ❤️
