### ISSUE TITLE
Problems with Apester

### ISSUE THREAD

**Issue by pereMatarin** [prebid/prebid-server-java#2030]
Hi! I'm Pere, from the tappx it team.

We have been investigating an issue we had with Apester, which uses your wrapper. We have seen in the requests that they do not send any cookies, could you help us with this issue?

Thanks!

**Comment by bretg** [comment]
@pereMatarin - we need more info.

1) when you say "uses your wrapper", are you referring to Prebid.js or Prebid Server?
2) when you say "send cookies", do you mean IDs? Please note that Prebid Server is not a browser, so of course it's not going to send cookies. By definition.
3) A test page is required.

**Comment by pereMatarin** [comment]
Responding to the sections:
    1- Prebid Server
    2- The problem is that the requests that come from magnite do not
receive the UUID parameter with our cookie, and as we see in the client our
cookie is not executed
    3- We don't have a test page, but you can prove it in Apester website :
https://apester.com/

Thanks!
