### ISSUE TITLE
GPP support defined in openRTB 2.6

### ISSUE THREAD

**Issue by radubarbos** [prebid/prebid-server-java#2098]
openRTB defined the GPP support through 2 new fields under BidRequest.Regs.
https://github.com/InteractiveAdvertisingBureau/openrtb2.x/blob/main/2.6.md#objectregs

The new fields should be supported by the server core.

**Comment by bretg** [comment]
Thanks @radubarbos - this is being tracked in https://github.com/prebid/prebid-server/issues/2380
