### ISSUE TITLE
GPP information in openRTB 2.5 adapters.

### ISSUE THREAD

**Issue by radubarbos** [prebid/prebid-server-java#2131]
The GPP information is not made available into the openRTB 2.5 adapters when the auction request is openRTB 2.6.

The BidRequestOrtb26To25Converter class provides in the modifyRegs method the **gdpr** and the **usPrivacy** data but not **gpp**.

```
final ExtRegs extRegs = ExtRegs.of(gdpr, usPrivacy);
copyProperties(regs.getExt(), extRegs);
```

The gpp should be provided under the extension object.

**Comment by bretg** [comment]
@radubarbos - As far as we know, regs.ext.gpp was never formalized. It was in a June 2022 draft, but ended up going directly into regs.gpp. So we would prefer that you upgrade your adapter to be able to handle ORTB 2.6.

What it takes to support 2.6 is:
- don't crash on unknown fields
- support regs.gdpr, regs.us_privacy, source.schain, user.consent, and user.eids.

However, as an interim, we would accept a community pull request that changes the downgrade behavior for regs.gpp and regs.gpp_sid.

**Comment by bretg** [comment]
> Are you saying that until our backend are updated we can not send gpp info?

The point of an "adapter" has always been to prepare the Prebid Server request for the backend. If your backend doesn't understand 2.6, there's always an option to do the "down-converting" yourself -- i.e. move regs.gdpr to regs.ext.gdpr, etc.

So those are your choices:

- change your adapter to accept 2.6 fields and do whatever conversion/moving needed 
- submit a PR against PBS-core's downgrade code change the regs.gpp downgrade behavior. We're very busy right now and could use the help. If you absolutely cannot do this, will try to squeeze this in the next few weeks.

**Comment by radubarbos** [comment]
Thank you for the information.
We'll change our adapter to do the conversion ourselves, we feel it's the fastest approach and we can control better what it's sent to our back-ends until they support openRTB 2.6. 
This issue can be closed.

**Comment by bretg** [comment]
Awesome thanks. Yes, we agree that the purpose of an adapter is to adapt to whatever the backend needs!
