### ISSUE TITLE
Developer Documentation - How to run unit tests?

### ISSUE THREAD

**Issue by maxime-dupuis** [prebid/prebid-server-java#2471]
The link for unit tests is dead: https://github.com/prebid/prebid-server-java/blob/master/README.md?plain=1#L108
(https://github.com/prebid/prebid-server-java/blob/master/docs/developers/unit-tests.md) 

I'd like documentation on how to
- run all the unit tests
  - `mvn test`
- run a single unit test file
  - `mvn test -Dtest="SharethroughBidderTest"`
- run a single unit test
  - `mvn test -Dtest="SharethroughBidderTest#makeHttpRequestsShouldCorrectlyAddHeaders"`

**Comment by bretg** [comment]
@SerhiiNahornyi - are unit tests the same as functional tests? If these examples are correct, please add them into one of the docs?
