### ISSUE TITLE
Devcontainer to simplify the development setup

### ISSUE THREAD

**Issue by maxime-dupuis** [prebid/prebid-server-java#2518]
The "dev container" tool simplifies the development setup for the Golang Prebid Server. It would be nice to have the same thing for this Java repo.

https://github.com/prebid/prebid-server/tree/master/.devcontainer

**Comment by maxime-dupuis** [comment]
My team is looking into this as a side project, but if anyone has experience with DevContainers your help is welcome!

**Comment by muuki88** [comment]
Are you using VS Code for Java development? I'm curious what your experience is. Most devs I know use intellij, very few Eclipse or Netbeans.

**Comment by maxime-dupuis** [comment]
@muuki88 Yes I'm using VSCode, but I didn't give it much thought. It's just because our internal projects are in Typescript and VSCode works well with them, + my IDE was already setup for other stuff like Git, Copilot, preferences, etc.

VSCode code works really well with the Golang Prebid-Server especially when you use the DevContainer (last week I setup a colleague in 2 minutes). We were really impressed and might even start using a DevContainer in our internal projects!
Not so much with this Java repo, it's red squiggly lines hell. So I'm looking for easy ways to get an IDE setup so my team and I can contribute more easily. My ideal world is if I can just fire up my IDE and it knows which Java version to install, how to run the unit tests, tell me if I have syntax errors, etc.

Good idea to use Intellij, I worked with it in a previous job and it was great. We might fall back on that if DevContainer doesn't work!

**Comment by maxime-dupuis** [comment]
Done!
