### ISSUE TITLE
wrong calls to the TCF vendor list

### ISSUE THREAD

**Issue by HeinzBaumann** [prebid/prebid-server-java#2755]
We are seeing a large number of calls coming through the rubiconproject datacenter that tries to access the TCF vendor list /v3/archives/vendor-list-v208.json. The only place I found where this URL is used is in the prebid server implementations. There is some logic in [src/main/resources/application.yaml](https://github.com/prebid/prebid-server-java/blob/239f12e650852ea4f1c439d3e43c9415a4ceb80b/src/main/resources/application.yaml#L216) where it constructs that URL. I also found somewhere a call to a specific version of the GVL (version 42) which for v3 doesn't exist either.
Not sure whether this is on this library end or one of the companies using this library that passes in a version that doesn't work for v3. The logic in this module will need to be updated as the version is always going to be different between v2 and v3. 
Please review and revise that piece of code as soon as possible as it is costing IAB EU quite some money for all these erroneous calls.

**Comment by bretg** [comment]
Closing as duplicate -- tracked by https://github.com/prebid/prebid-server/issues/3292
