### ISSUE TITLE
Java SDK version issue

### ISSUE THREAD

**Issue by yuhaoban** [prebid/prebid-server-java#2831]
Hi,
I tried to build the project with Java 11, 17, 21 but failed with all of these versions. Only Java 18 works on my side. Does this only happen to me or someone else as well?

**Comment by KolomiietsSerhii** [comment]
Hi, @yuhaoban

Could you, please, share with us yours workflow and Java-related env. configs that was used for build? Thx!

We all are using Java 17 (17.0.4+11-LTS-179) and bundled Maven wrapper (v3.8.6).

**Comment by SerhiiNahornyi** [comment]
@yuhaoban Have you already resolved this issue?

**Comment by yuhaoban** [comment]
Hi @KolomiietsSerhii @SerhiiNahornyi 
No, I still only can run the project with java 18.
I'm using Java 18 (build 18.0.2+9-61) and Maven (v3.9.6).

**Comment by KolomiietsSerhii** [comment]
> Hi @KolomiietsSerhii @SerhiiNahornyi No, I still only can run the project with java 18. I'm using Java 18 (build 18.0.2+9-61) and Maven (v3.9.6).

Would nice to see error log. Thx.

**Comment by bretg** [comment]
@yuhaoban - please provide an error log for what happens when you try to build with Java 17.

**Comment by yuhaoban** [comment]
Hi @bretg - Truly sorry for the late reply. I have already resolved the issue after reinstalling the Java 17. Thank you for following up.
