### ISSUE TITLE
Unnecessary calls to vendor list provider

### ISSUE THREAD

**Issue by SerhiiNahornyi** [prebid/prebid-server-java#2840]
As for now `VendorListService` will try to infinitely re-fetch vendor list for invalid version. This causes millions of calls to vendor list provider server. 

Proposed solution:
 - Add exponential backoff for failed downloads

**Comment by bretg** [comment]
Related to https://github.com/prebid/prebid-server/issues/3336

**Comment by And1sS** [comment]
Also related to https://github.com/prebid/prebid-server/issues/3405

**Comment by And1sS** [comment]
Fixed in https://github.com/prebid/prebid-server-java/pull/2919

**Comment by And1sS** [comment]
Fixed in https://github.com/prebid/prebid-server-java/pull/2919
