### ISSUE TITLE
Metrics Documentation Outdated Re: `/cookie_sync` endpoint metrics

### ISSUE THREAD

**Issue by kuleszaj** [prebid/prebid-server-java#3017]
The "`/cookie_sync` endpoint metrics" section of the [Metrics documentation](https://github.com/prebid/prebid-server-java/blob/master/docs/metrics.md#cookie_sync-endpoint-metrics) seems to be out of date.

It lists `cookie_sync.<bidder-name>.gen` and `cookie_sync.<bidder-name>.matches` as available metrics, but neither seems to be available anymore, and it looks like they were removed:
- https://github.com/prebid/prebid-server-java/issues/2114
- https://github.com/prebid/prebid-server-java/pull/2065
  - In particular, https://github.com/prebid/prebid-server-java/pull/2065/files#diff-fcd88b249295823c1877f78f5e06d5c8119384d522032b15eecca80b7bb24d55L80-L81

Submitted PR for adjusting the documentation at: https://github.com/prebid/prebid-server-java/pull/3016

**Comment by Net-burst** [comment]
Closing this issue as the PR with the update was merged. Thanks for your contribution, @kuleszaj
