### ISSUE TITLE
Exceptions handling (null handling)

### ISSUE THREAD

**Issue by amanpatniajmer** [prebid/prebid-server-java#3034]
There were no null checks on some of the fields, due to which we are seeing high number of exceptions. Following are the issues found during profiling - 
<img width="1312" alt="image" src="https://github.com/prebid/prebid-server-java/assets/34913883/db51f89a-6b23-43aa-a2f2-04654d1daa71">

1. SetUidGppService.toInt() - NumberFormatException
2. PubmaticBidder.parsedKADFloor() - NumberFormatException
3. Ccpa.isEnforced() - PrebidException

Attaching PR to fix handle these exceptions - 
https://github.com/prebid/prebid-server-java/pull/3035

**Comment by amanpatniajmer** [comment]
@Net-burst any update on this?

**Comment by Net-burst** [comment]
@amanpatniajmer hi. Sorry for the delay. This is still on our plate. We should be able to get to the issue pretty soon.

**Comment by amanpatniajmer** [comment]
@Net-burst got merged.

**Comment by Net-burst** [comment]
Yeah, thanks for your contribution @amanpatniajmer ! Closing this issue.
