### ISSUE TITLE
Ad requests not converting to impressions

### ISSUE THREAD

**Issue by dzesm** [prebid/prebid-server-java#3192]
Hello,

We have a problem with our requests converting into impressions since 15.04. Basically, all of the impressions dropped to 0 without any significant changes in our application and frontend code. 

I have found some similar issues from a few years ago, but they are regarding ad requests dropping, not impressions.

We are trying to find the issue here, but cannot pinpoint what could be the problem. 
Do you have any experience with this and is this problem most likely to be related to PBS, our server configuration or the ad manager itself?

Thank you for your help.

**Comment by SerhiiNahornyi** [comment]
@dzesm There are no known issues with PBS. Is this problem still occurring for you?

**Comment by bretg** [comment]
@dzesm - there's not nearly enough information to work with here. Feel free to open an issue with details if it's still something you're dealing with.

e.g. where are you seeing the impression loss - ad server? PBJS analytics? PBS analytics? web? mobile app?
Are you seeing bid responses? renders? What version are you running?
