### ISSUE TITLE
Support for logging metrics with Logback 

### ISSUE THREAD

**Issue by ianwow** [prebid/prebid-server-java#3249]
This is a feature request.

**Problem:** 
Metrics cannot be configured with the standard logging properties described in https://github.com/prebid/prebid-server-java/blob/master/docs/config.md#logging-properties

**Proposed Solution:**
Add a log reporter in `src/main/java/org/prebid/server/spring/config/metrics/MetricsConfiguration.java` that enables users to activate metric logging from `prebid-config.yaml` with options specified in logback configuration files (e.g. `prebid-logging.xml`) as mentioned in https://github.com/prebid/prebid-server-java/blob/master/docs/config.md#logging-properties

**Comment by SerhiiNahornyi** [comment]
Closed as done, feel free to re-open if you have other questions
