### ISSUE TITLE
No Docker images being published

### ISSUE THREAD

**Issue by brushmate** [prebid/prebid-server-java#3376]
A while ago I asked if you could publish Docker images in #2426 and it was kind of implemented in #2884. But apperently the workflow is disabled and Docker images are still not being published? Was it simply forgotten or did you ditch the idea?

**Comment by Compile-Ninja** [comment]
Thank you for the reminder! We appreciate you bringing this to our attention. One of our developers (@And1sS ) is currently working on it, so you can expect this to be available in one or two upcoming releases. We'll make sure to keep you updated on the progress.

**Comment by And1sS** [comment]
Addressed this issue in https://github.com/prebid/prebid-server-java/pull/3408, now you can check images here: https://github.com/prebid/prebid-server-java/pkgs/container/prebid-server-java

**Comment by Net-burst** [comment]
There is a plan to add Docker Hub push too, but it'll happen a bit later.
