### ISSUE TITLE
PBS prebuilt Docker images not available in GitHub packages

### ISSUE THREAD

**Issue by thyagram-aws** [prebid/prebid-server-java#3420]
According to the PBS GitHub [documentation](https://github.com/prebid/prebid-server-java?tab=readme-ov-file#running-docker-image), we can download prebuilt Docker images from [GitHub Packages](https://github.com/orgs/prebid/packages?repo_name=prebid-server-java) page. However the link seems to provide no results.

**Comment by bretg** [comment]
Updated permissions -- please try again @thyagram-aws ?
