### ISSUE TITLE
Greenbids adapter depends on a none existing file in tests

### ISSUE THREAD

**Issue by muuki88** [prebid/prebid-server-java#3629]
The `GreenbidsRealTimeDataProcessedAuctionRequestHookTest` seems to try downloading a, what seems to be [pirated version of MaxMinds GeoLite database](https://github.com/P3TERX/GeoLite.mmdb/tree/download). We should remove this for many reasons (external dependencies, probably pirated db, no offline tests possible, random failures if files not available)

The project even explicitly removes older releases:
https://github.com/P3TERX/GeoLite.mmdb/blob/3bd5ebd7734fcdb863b0d92b96d2e6aa3c1580f4/.github/workflows/GeoLite.yml#L74-L77

## Error log

From https://github.com/prebid/prebid-server-java/actions/runs/12314480990/job/34370688356?pr=3622#step:6:7155

```
Error:  Errors: 
Error:    GreenbidsRealTimeDataProcessedAuctionRequestHookTest.setUp:96->givenDatabaseReader:343 » FileNotFound https://github.com/P3TERX/GeoLite.mmdb/releases/download/2024.12.13/GeoLite2-Country.mmdb
Error:    GreenbidsRealTimeDataProcessedAuctionRequestHookTest.setUp:96->givenDatabaseReader:343 » FileNotFound https://github.com/P3TERX/GeoLite.mmdb/releases/download/2024.12.13/GeoLite2-Country.mmdb
Error:    GreenbidsRealTimeDataProcessedAuctionRequestHookTest.setUp:96->givenDatabaseReader:343 » FileNotFound https://github.com/P3TERX/GeoLite.mmdb/releases/download/2024.12.13/GeoLite2-Country.mmdb
Error:    GreenbidsRealTimeDataProcessedAuctionRequestHookTest.setUp:96->givenDatabaseReader:343 » FileNotFound https://github.com/P3TERX/GeoLite.mmdb/releases/download/2024.12.13/GeoLite2-Country.mmdb

**Comment by AntoxaAntoxic** [comment]
Fixed in https://github.com/prebid/prebid-server-java/pull/3624
