### ISSUE TITLE
Unit test bug related to GDPR=false

### ISSUE THREAD

**Issue by maddapper** [prebid/prebid-server-java#858]
So, when I try to run maven package with GDPR set to false, I am getting unit test failure(s).  Is this expected unit test behavior?

`[ERROR] Failures: 
[ERROR]   ApplicationTest.cookieSyncShouldReturnBidderStatusWithExpectedUsersyncInfo:362 
Expecting:
  <[BidderUsersyncStatus(bidder=adform, error=null, noCookie=true, usersync=UsersyncInfo(url=//adform-usersynchttp%3A%2F%2Flocalhost%3A8000%2Fsetuid%3Fbidder%3Dadform%26gdpr%3D1%26gdpr_consent%3DBO4C5JrO4C5JrAAAAAktBPoAAAAGRAAAAAgAAIAAAAAAAAA%26us_privacy%3D1YNN%26uid%3D%24UID, type=redirect, supportCORS=false)),
    BidderUsersyncStatus(bidder=appnexus, error=null, noCookie=true, usersync=UsersyncInfo(url=//usersync-url/getuid?http%3A%2F%2Flocalhost%3A8000%2Fsetuid%3Fbidder%3Dadnxs%26gdpr%3D1%26gdpr_consent%3DBO4C5JrO4C5JrAAAAAktBPoAAAAGRAAAAAgAAIAAAAAAAAA%26us_privacy%3D1YNN%26uid%3D%24UID, type=redirect, supportCORS=false)),
    BidderUsersyncStatus(bidder=rubicon, error=null, noCookie=true, usersync=UsersyncInfo(url=http://localhost:8000/setuid?bidder=rubicon&gdpr=1&gdpr_consent=BO4C5JrO4C5JrAAAAAktBPoAAAAGRAAAAAgAAIAAAAAAAAA&us_privacy=1YNN&uid=host-cookie-uid, type=redirect, supportCORS=false))]>
to contain only:
  <[BidderUsersyncStatus(bidder=rubicon, error=null, noCookie=true, usersync=UsersyncInfo(url=http://localhost:8000/setuid?bidder=rubicon&gdpr=1&gdpr_consent=BO4C5JrO4C5JrAAAAAktBPoAAAAGRAAAAAgAAIAAAAAAAAA&us_privacy=1YNN&uid=host-cookie-uid, type=redirect, supportCORS=false)),
    BidderUsersyncStatus(bidder=appnexus, error=null, noCookie=true, usersync=UsersyncInfo(url=//usersync-url/getuid?http%3A%2F%2Flocalhost%3A8000%2Fsetuid%3Fbidder%3Dadnxs%26gdpr%3D1%26gdpr_consent%3DBO4C5JrO4C5JrAAAAAktBPoAAAAGRAAAAAgAAIAAAAAAAAA%26us_privacy%3D1YNN%26uid%3D%24UID, type=redirect, supportCORS=false)),
    BidderUsersyncStatus(bidder=adform, error=Rejected by TCF, noCookie=null, usersync=null)]>
elements not found:
  <[BidderUsersyncStatus(bidder=adform, error=Rejected by TCF, noCookie=null, usersync=null)]>
and elements not expected:
  <[BidderUsersyncStatus(bidder=adform, error=null, noCookie=true, usersync=UsersyncInfo(url=//adform-usersynchttp%3A%2F%2Flocalhost%3A8000%2Fsetuid%3Fbidder%3Dadform%26gdpr%3D1%26gdpr_consent%3DBO4C5JrO4C5JrAAAAAktBPoAAAAGRAAAAAgAAIAAAAAAAAA%26us_privacy%3D1YNN%26uid%3D%24UID, type=redirect, supportCORS=false))]>
[ERROR] Errors: 
[ERROR]   ApplicationTest.openrtb2AuctionShouldRespondWithBidsFromRubiconAndAppnexus:136->IntegrationTest.lambda$openrtbCacheDebugComparator$1:171 » Runtime
[INFO] 
[ERROR] Tests run: 2874, Failures: 1, Errors: 1, Skipped: 0
[INFO] 
`

**Comment by maddapper** [comment]
Here is the relevant part of my config:
`gdpr:
  enabled: false
  default-value: 1`

**Comment by DGarbar** [comment]
Thanks for creating the issue.
Fixed in https://github.com/rubicon-project/prebid-server-java/pull/861
